update with last debug

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,7 +24,7 @@ jobs:
       run:
         working-directory: ./deployment
     name: Terraform Plan
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -44,27 +44,27 @@ jobs:
         id: validate
         run: terraform validate -no-color
 
-      # - name: tfsec
-      #   uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
-      #   with:
-      #     tfsec_args: --soft-fail
-      #     github_token: ${{ github.token }}
+      - name: tfsec
+        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
+        with:
+          tfsec_args: --soft-fail
+          github_token: ${{ github.token }}
 
       - name: Terraform Plan
         id: plan
         run: |
-          #export exitcode=0
-          terraform plan -no-color -var-file="./tfvars/terraform.tfvars" -out=main.tfplan >> $GITHUB_OUTPUT
+          export exitcode=0
+          terraform plan -no-color -var-file="./tfvars/terraform.tfvars" -out main.tfplan || export exitcode=$?
 
-          #echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
 
-          # if [ $exitcode -eq 1 ]; then
-          #   echo "Error: Terraform plan failed"
-          #   exit 1
-          # else
-          #   echo "Terraform plan was successful"
-          #   exit 0
-          # fi
+          if [ $exitcode -eq 1 ]; then
+            echo "Error: Terraform plan failed"
+            exit 1
+          else
+            echo "Terraform plan was successful"
+            exit 0
+          fi
         
       - name: Publish Terraform Plan
         uses: actions/upload-artifact@v4
@@ -72,81 +72,81 @@ jobs:
           name: tfplan
           path: ./deployment/main.tfplan
 
-      # - name: Update Pull Request
-      #   uses: actions/github-script@v6
-      #   env:
-      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      #   with:
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     script: |
-      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      - name: Update Pull Request
+        uses: actions/github-script@v6
+        env:
+          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
   
-      #       <details><summary>Show Plan</summary>
+            <details><summary>Show Plan</summary>
   
-      #       \`\`\`\n
-      #       ${process.env.PLAN}
-      #       \`\`\`
+            \`\`\`\n
+            ${process.env.PLAN}
+            \`\`\`
   
-      #       </details>
+            </details>
   
-      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
   
-      #       github.rest.issues.createComment({
-      #         issue_number: context.issue.number,
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         body: output
-      #       })
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })
       
-      # - name: Terraform Plan Status
-      #   if: steps.plan.outcome == 'failure'
-      #   run: exit 1
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
 
-      # - name: Create String Output
-      #   id: tf-plan-string
-      #   run: |
-      #       TERRAFORM_PLAN=$(terraform show -no-color main.tfplan)
+      - name: Create String Output
+        id: tf-plan-string
+        run: |
+            TERRAFORM_PLAN=$(terraform show -no-color main.tfplan)
             
-      #       delimiter="$(openssl rand -hex 8)"
-      #       echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-      #       echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-      #       echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-      #       echo "" >> $GITHUB_OUTPUT
-      #       echo '```terraform' >> $GITHUB_OUTPUT
-      #       echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-      #       echo '```' >> $GITHUB_OUTPUT
-      #       echo "</details>" >> $GITHUB_OUTPUT
-      #       echo "${delimiter}" >> $GITHUB_OUTPUT
+            delimiter="$(openssl rand -hex 8)"
+            echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+            echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+            echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+            echo "" >> $GITHUB_OUTPUT
+            echo '```terraform' >> $GITHUB_OUTPUT
+            echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+            echo '```' >> $GITHUB_OUTPUT
+            echo "</details>" >> $GITHUB_OUTPUT
+            echo "${delimiter}" >> $GITHUB_OUTPUT
 
-      # - name: Publish Terraform Plan to Task Summary
-      #   env:
-      #     SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-      #   run: |
-      #     echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+      - name: Publish Terraform Plan to Task Summary
+        env:
+          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+        run: |
+          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
 
-      # - name: Push Terraform Output to PR
-      #   if: github.ref != 'refs/heads/main'
-      #   uses: actions/github-script@v7
-      #   env:
-      #     SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
-      #   with:
-      #       github-token: ${{ secrets.GITHUB_TOKEN }}
-      #       script: |
-      #           const body = `${process.env.SUMMARY}`;
-      #           github.rest.issues.createComment({
-      #               issue_number: context.issue.number,
-      #               owner: context.repo.owner,
-      #               repo: context.repo.repo,
-      #               body: body
-      #           })
+      - name: Push Terraform Output to PR
+        if: github.ref != 'refs/heads/main'
+        uses: actions/github-script@v7
+        env:
+          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+        with:
+            github-token: ${{ secrets.GITHUB_TOKEN }}
+            script: |
+                const body = `${process.env.SUMMARY}`;
+                github.rest.issues.createComment({
+                    issue_number: context.issue.number,
+                    owner: context.repo.owner,
+                    repo: context.repo.repo,
+                    body: body
+                })
 
   terraform-apply:
     needs: terraform-plan
     name: Terraform Apply
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     environment: dev
     defaults:
       run:
