updates

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,97 +1,192 @@
-name: Deploy Infra
-on:
-  push:
-    branches:
-      - main
-    paths:
-      - 'deployment/**'
-  workflow_dispatch:
-
+name: "Terraform"
 permissions:
   contents: read
   id-token: write
   pull-requests: write
 
-env:
-  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-  ARM_USE_AZUREAD: true
+on:
+  workflow_dispatch:
+    inputs:
+      # Working directory input from user.
+      resource:
+        type: choice
+        description: Choose the resource
+        options:
+        - deployment
+        - deployment
+      # Terraform action you want to perform
+      action:
+        description: 'Terraform Action to Perform'
+        type: choice
+        options:
+        - Terraform_apply
+        - Terraform_destroy
 
 jobs:
-  terraform-plan:
+  terraform_apply:
+    name: "Terraform_apply"
+    if: ${{ github.event.inputs.action == 'Terraform_apply' }}
+    runs-on: ubuntu-latest
     defaults:
       run:
-        working-directory: ./deployment
-    name: Terraform Plan
-    runs-on: ubuntu-latest
+        working-directory: ${{ github.event.inputs.resource }}
     steps:
-      - name: Checkout code
+      - name: Checkout
         uses: actions/checkout@v2
 
       - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-
-      - name: Terraform Fmt
-        id: fmt
-        run: terraform fmt -check
+        uses: hashicorp/setup-terraform@v1
 
       - name: Terraform Init
         id: init
-        run: terraform init -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}"
-
+        run: terraform init
+        env:
+          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+          ARM_USE_AZUREAD: true
+      
       - name: Terraform Validate
         id: validate
         run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        run: |
-          export exitcode=0
-          terraform plan -no-color -var-file="./tfvars/terraform.tfvars" -out main.tfplan || export exitcode=$?
+      - name: Terraform Apply
+        id: apply
+        run: terraform apply -auto-approve -var-file=variables.tfvars
+        env:
+          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+          ARM_USE_AZUREAD: true
 
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-
-          if [ $exitcode -eq 1 ]; then
-            echo "Error: Terraform plan failed"
-            exit 1
-          else
-            echo "Terraform plan was successful"
-            exit 0
-          fi
-        
-      - name: Publish Terraform Plan
-        uses: actions/upload-artifact@v4
-        with:
-          name: tfplan
-          path: ./deployment/main.tfplan
-
-      
-  terraform-apply:
-    needs: terraform-plan
-    name: Terraform Apply
+  terraform_destroy:
+    name: "Terraform_destroy"
+    if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
     runs-on: ubuntu-latest
-    environment: dev
     defaults:
       run:
-        working-directory: ./deployment
-
+        working-directory: ${{ github.event.inputs.resource }}
     steps:
-      - name: Checkout code
+      - name: Checkout
         uses: actions/checkout@v2
 
       - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
+        uses: hashicorp/setup-terraform@v1
 
       - name: Terraform Init
         id: init
-        run: terraform init -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}"
+        run: terraform init
+        env:
+          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+          ARM_USE_AZUREAD: true
+      
+      - name: Terraform Destroy
+        id: destroy
+        working-directory: ${{ github.event.inputs.resource }}
+        run: terraform destroy -auto-approve -var-file=variables.tfvars
+        env:
+          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+          ARM_USE_AZUREAD: true
 
-      - name: Download Terraform Plan
-        uses: actions/download-artifact@v4
-        with:
-          name: tfplan
-          path: ./deployment
 
-      - name: Terraform Apply
-        run: terraform apply -auto-approve "./main.tfplan"
+# name: Deploy Infra
+# on:
+#   push:
+#     branches:
+#       - main
+#     paths:
+#       - 'deployment/**'
+#   workflow_dispatch:
+
+# permissions:
+#   contents: read
+#   id-token: write
+#   pull-requests: write
+
+# env:
+#   ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+#   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+#   ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+#   ARM_USE_AZUREAD: true
+
+# jobs:
+#   terraform-plan:
+#     defaults:
+#       run:
+#         working-directory: ./deployment
+#     name: Terraform Plan
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v2
+
+#       - name: Terraform Fmt
+#         id: fmt
+#         run: terraform fmt -check
+
+#       - name: Terraform Init
+#         id: init
+#         run: terraform init -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}"
+
+#       - name: Terraform Validate
+#         id: validate
+#         run: terraform validate -no-color
+
+#       - name: Terraform Plan
+#         id: plan
+#         run: |
+#           export exitcode=0
+#           terraform plan -no-color -var-file="./tfvars/terraform.tfvars" -out main.tfplan || export exitcode=$?
+
+#           echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+#           if [ $exitcode -eq 1 ]; then
+#             echo "Error: Terraform plan failed"
+#             exit 1
+#           else
+#             echo "Terraform plan was successful"
+#             exit 0
+#           fi
+        
+#       - name: Publish Terraform Plan
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: tfplan
+#           path: ./deployment/main.tfplan
+
+      
+#   terraform-apply:
+#     needs: terraform-plan
+#     name: Terraform Apply
+#     runs-on: ubuntu-latest
+#     environment: dev
+#     defaults:
+#       run:
+#         working-directory: ./deployment
+
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v2
+
+#       - name: Terraform Init
+#         id: init
+#         run: terraform init -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}"
+
+#       - name: Download Terraform Plan
+#         uses: actions/download-artifact@v4
+#         with:
+#           name: tfplan
+#           path: ./deployment
+
+#       - name: Terraform Apply
+#         run: terraform apply -auto-approve "./main.tfplan"
